#!/bin/bash

read -p "Voulez-vous générer un fichier d'information de commit (y/[n]) ?" yn < /dev/tty
yn=${yn:-n}
case $yn in
 [Yy]* )
 echo "commit vérifié le $(date)" > suivi/commitInfo.txt
 git add suivi/commitInfo.txt
 exit 0;;
 [Nn]* )
 exit 0;;
esac
exit 0
